pipeline {
    agent any
    
    stages {
        stage('Hello World') { 
            steps {
                echo "Way to go, ${targetName}!"
            }
        }
        stage('Wait') { 
            steps {
                sleep 60 
            }
        }
    }

    post {
      success {  
        echo "SUCCESSFUL RUN!"
      }

      failure {
        echo "FAILED RUN!"
      }

      aborted {
        echo "ABORTED RUN!"
      }
  }
}